name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: SpringBootChapter1Test
      id: springbootchapter1test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: SpringBootChapter1Test
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SPRINGBOOTCHAPTER1TEST_RESULTS: "${{steps.springbootchapter1test.outputs.result}}"
      with:
        runners: springbootchapter1test
